---
- name: Install misc packages
  apt:
    name: '{{item}}'
    state: present
    cache_valid_time: 86400
  with_items: '{{ common_packages }}'

- name: Increase entropy
  apt:
    name: 'haveged'
    state: present

- name: Ensure /var/www/ exists
  file:
    path: /var/www/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: set locale to utf-8
  shell: update-locale LC_ALL={{ common_locale }}
  changed_when: false
  tags: ['skip_ansible_lint']

- name: set default locale
#  become: yes
  lineinfile:
    dest: /etc/default/locale
    regexp: '^LC_ALL'
    line: 'LC_ALL={{ common_locale }}'
