---
- name: Install misc packages
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{ common_packages }}'

- name: Increase entropy
  apt:
    name: 'haveged'
    state: present

- name: Ensure /var/www/ exists
  file:
    path: /var/www/
    state: directory
    owner: root
    group: root
    mode: '0755'